Update Shield-Changelog.md
EricomSoftwareLtd/Shield pull request #1057
Opened 2021-01-18 11:24 UTC by BenyH

2021-01-18 11:26 UTC, ErezPasternak approved these changes

2021-01-18 16:42 UTC, RachelShemberg requested changes
@BenyH please review my suggestion:

### New Features

- Admin Auditing - New functionality and new reports 
- Admin SAML Authentication - support ADFS
- Admin SAML Authentication - Support proxy mode
- Proxy Chain - Shield Integration with DLP Systems
- Start-up process redesigned

### Enhancements

- Security Improvements
- Admin login is blocked after several failed login attempts
- Move Log Infrastructure to filebeat+logstash
- Align Auth-proxy logs collected as other containers
- clean-rancher-agent will not remove kube config file by default
- Domain policy to be case insensitive
- Unify shield-ova and registry-ova
- Update Display Name from AD on Profile All Users in Shield
- Increase Config Backup History Length to 30 days

### Bug Fixes

- Fixed: Github website displays message "browser version is not supported"
- Fixed: UPS website popups not working
- Fixed: Double Click in google drive not opening files
- Fixed: store.ferrari.com in Crystal issues
- Fixed: Page jumps without user input
- Fixed: PDF issue at bar123.co.il 
- Fixed: Japanese KB - space key is not working as expected in FF
- Fixed: docker version in shield-prepare-servers (GitHub #727)
- Fixed: External Objects for the checkSessionLimit = true scenario (CA0000068373)

2021-01-18 17:30 UTC, BenyH commented
What does it mean?:
Admin SAML Authentication - support ADFS => do you mean: Admin SAML Authentication (also using ADFS)
Admin SAML Authentication - Support proxy mode => i don;t understand

2021-01-19 09:29 UTC, RachelShemberg approved these changes

2021-01-19 09:38 UTC, merged